### ISSUE TITLE
Howdy!

### ISSUE THREAD

**Issue by thheller** [cjohansen/replicant#16]
I'm reaching out because I believe our goals are somewhat aligned and would like to discuss something.

As you are aware I started work on [shadow-grove](https://github.com/thheller/shadow-grove) quite some time ago. I actually started the underlying [shadow-arborist](https://github.com/thheller/shadow-arborist) even earlier, but decided to roll that into one library because it saves time not having to maintain separate repos/libraries.

Now, I'm not here to convince you to adopt `shadow-grove`, because that goes way beyond the scope of what `replicant` is. What I would like to discuss is `shadow.arborist`. Or to be even more specific [two actual protocols](https://github.com/thheller/shadow-grove/blob/305600ab696998f610a9940c5da4d209110c64db/src/main/shadow/arborist/protocols.cljs#L3-L26)  (ignore IDirectUpdate for now).

```clojure
(defprotocol IManaged
  (^boolean supports? [this next])
  (dom-sync! [this next])

  (dom-insert [this parent anchor])
  (dom-first [this])

  ;; called after all nodes managed by this have been added to the actual document
  ;; might be immediately after dom-insert but may be delayed when tree is constructed
  ;; offscreen by something like suspense
  ;; implementations must properly propagate this to children if needed
  (dom-entered! [this])

  ;; if parent node was already removed from DOM the children
  ;; don't need to bother removing themselves again
  (destroy! [this ^boolean dom-remove?]))

(defprotocol IConstruct
  :extend-via-metadata true
  (as-managed [this env]))
```

## Why are these useful?

They form the basic abstraction you need to first construct a DOM tree, via `IConstruct` and then `dom-insert` into the DOM. On a repeated cycle check whether it can be updated (via `supports?`) and if so `dom-sync!` it, or create the replacement, by first `dom-insert`-ing the replacement before the `dom-first` of the old variant, and then `destroy!`-ing the old one.

So, they cover the entire typical render/diff/update lifecycle we all love.

The essential thing here is that these are extensible protocols. Arborist itself doesn't have components. Grove does, but there could be alternate implementations. I actually think that the current components are not the best solution for how to handle components. Just the best I have come up with far, in my entirely subjective opinion.

I do however believe that the arborist protocols are somewhat "good". At least I have not seen anything that didn't end up needing exactly those ops. I'm totally open to being convinced otherwise though.

## My Wish

The point is there can be many different implementations of these protocols. As long as the implementations follow the rules they can all interop with each other just fine. Which is why I'm here.

I think the CLJS community is currently too small, and having many different options for frontend might not be helping. I mean to be honest the "correct" recommendation is using `react`, given its ecosystem. I'd like something pure CLJS though. 

So, instead of having many different "competing" CLJS implementations, why not start with something that can work together and let users choose which state management solution they like best. If we want a pure CLJS ecosystem we gotta start somewhere.

## Current State

I have used `shadow-grove` for a long time now and recently starting working on it again. I want to push it to a place, with actual docs, where I can recommend it to people. Today I fixed a bug in the interpreted hiccup implementation, which makes it actually competitive in speed with others.

So interpreted hiccup benchmark ends up here:
- https://github.com/thheller/js-framework-shadow-grove?tab=readme-ov-file#2024-02-07

and the more optimize "fragment" implementation ends up ~20% faster
- https://github.com/thheller/js-framework-shadow-grove?tab=readme-ov-file#2024-01-11

The grove variants then end up somewhere inbetween, but they end up doing a bunch more stuff (EQL, normalized DB, etc). Both "Ultralight" variants basically only use the arborist parts and not grove.

The Interpreted Hiccup variant looks close to what `replicant` currently looks like
- https://github.com/thheller/js-framework-shadow-grove/blob/master/src/main/bench/ultralight_interpreted.cljs

I didn't run the `replicant` benchmark, so not sure where this ends up. I'm not really here to compare benchmarks that are mostly meaningless. Just presenting that there is a decent solution built on **extensible protocols**, which I hope sparks some interest.

I only glanced over the `replicant` code a little bit, but couldn't find a comparable protocol. So, I'm guessing the implementation is somewhat locked down, in the same way that `react` is. This is of course fine, but IMHO lacks in extensibility.

I'm somewhat confident that it is possible to build `replicant` on top of the arborist protocols, even if you completely replace the interpreted hiccup implementation in the process. I'm not saying that you should, just trying to reach out to discuss.

**Comment by thheller** [comment]
So, after sleeping on this I guess a different approach might be to limit the extensible part to only cases where they are actually necessary. So, keeping a your hiccup interpreter, but falling back to a common protocol if something is encountered that is not hiccup.

```clojure
;; staying entirely within replicant
[:div.foo "hello " [:strong "world"]]

;; ends up with non-hiccup, not sure how replicant currently handles this
[:div.foo "hello" (a-grove-component)]
```

I guess I'd like to avoid the interop situation that currently exists in `react`, where to interop with other libraries if have to use a `[:div {:ref ref} ...]` and `useEffect` then rendering into that `div` via `ref`. This is fine, but kinda wastes a `div`.

**Comment by cjohansen** [comment]
Howdy!

Thanks for taking the time to write this, you clearly put a lot of thought into it.

I am aware of shadow-grove, but as you expected, I didn't know about arborist until the relatively recent ClojureVerse discussion.

My main goal with Replicant is to have a pure rendering library that can turn fully serializable EDN data into a live DOM. Because of this starting point I hadn't really planned any features to handle opaque bits in the hiccup, so the current behavior is to `str` anything that isn't hiccup 😅 

> I didn't run the replicant benchmark, so not sure where this ends up. I'm not really here to compare benchmarks that are mostly meaningless. Just presenting that there is a decent solution built on extensible protocols, which I hope sparks some interest.

I've been down the same rabbit hole as you with that benchmark, so I had to run it to see 😄 

![image](https://github.com/cjohansen/replicant/assets/32871/9e12846c-6416-41ab-9523-9f884731e9f8)

Replicant is quite a bit slower than shadow-grove (this is the interpreted one). You're getting pretty impressive results, I'm quite curious how you did it, cause I've run out of ideas for anything other than minimal gains. But this benchmark did show me that I have had a regression in the swap and remove row cases, so I'll have to look into those. 

I know these benchmarks are not everything, but I don't think they're entirely meaningless.

> I only glanced over the replicant code a little bit, but couldn't find a comparable protocol. So, I'm guessing the implementation is somewhat locked down, in the same way that react is. This is of course fine, but IMHO lacks in extensibility.

There's not. Like I mentioned, Replicant's interface is data. This does of course limit the ability to mix in other libraries like you mentioned, but this is a use case I would almost never opt for in my own work (except for maybe a map or something), so I hadn't even considered it. But I do agree that it is not very extensible.

Replicant does use a [protocol](https://github.com/cjohansen/replicant/blob/main/src/replicant/protocols.cljc) to insulate itself from the DOM API. This is there primarily for testing and development purposes, but also means I can do server-side string rendering using the same algorithm. That is probably not the most efficient way to do that, but it would ensure that it would be built exactly the same way, which is a nice guarantee.

> I'm somewhat confident that it is possible to build replicant on top of the arborist protocols, even if you completely replace the interpreted hiccup implementation in the process. I'm not saying that you should, just trying to reach out to discuss.

If this can be achieved without sacrificing the pure data interface, I agree that it sounds like a good idea.

>So, after sleeping on this I guess a different approach might be to limit the extensible part to only cases where they are actually necessary. So, keeping a your hiccup interpreter, but falling back to a common protocol if something is encountered that is not hiccup.
>
>    ;; staying entirely within replicant
>    [:div.foo "hello " [:strong "world"]]
>
>    ;; ends up with non-hiccup, not sure how replicant currently handles this
>    [:div.foo "hello" (a-grove-component)]
>
>I guess I'd like to avoid the interop situation that currently exists in react, where to interop with other libraries if have to use a `[:div {:ref ref} ...]` and useEffect then rendering into that div via ref. This is fine, but kinda wastes a div.

I wasn't initially sure what the benefit of this protocol would offer users of Replicant, but this comment made it clearer for me, and I agree -- this looks useful. I actually started working on an idea in this direction yesterday. Being data-obsessed, the idea is to allow you to use namespaced keys for tag names, and have dispatch mechanism for these, e.g.:

```clj
[:div 
  [:h1 [:i18n/text :frontpage/title]]
  [:myapp/mapbox {:zoom-level 1}]]
```

The idea being that both `:i18n/text` and `:myapp/mapbox` would call on a function (but only when they need to (re-)render) to produce the necessary hiccup. These are kinda "data components" and something of an extension point (e.g. i18n) where you can do last minute changes to the data structure being rendered.

Your suggestion seems to me a more generalized version of this idea, and I think it should be possible combine them somehow. I like the idea of seemlessly being able to render "anything", but I don't want to encourage a bunch of opaque objects in the hiccup.

**Comment by thheller** [comment]
> Being data-obsessed, the idea is to allow you to use namespaced keys for tag names

I have been there myself. I decided not to use it because it creates a bit of a "maintenance hassle", meaning that you have to put the implementation for that keyword somewhere. So, the immediate first candiate becomes a `defmulti` or some other kind of registry atom. The hassle being that we cannot rely on your code structure to provide these, or my larger pet peeve being that dead-code elimination cannot work. Thus all registered components stay alive, even if never used. The the build-sized-obsessed me that didn't seem ideal.

Data orientation is also not lost with the protocol approach, although the current impls are often just `deftype`. For all of them I could have gone with `defrecord` instead, but that generates extra code thats often not needed. Bloating the build size ...

But in the end the way this always works is the for example calling `(a-grove-component)` does not actually immediately construct the component/DOM. It creates an initializer object, which I have struggled to name correctly. I kinda like "Seed" since it fits into this whole tree-analogy theme. The idea being that you place the seed and a tree grows out of it.

To make this less abstract `(def frag (<< [:div "hello: " name]))` does not create any DOM whatsoever. It creates an instance of [FragmentInit](https://github.com/thheller/shadow-grove/blob/2715cb8d163b4a1e37cc4d2b4e402b26d073ff5c/src/main/shadow/arborist/fragments.cljs#L120-L129), which waits until its `IConstruct` implementation is actually called to do any work.  `<<` being a macro allows everything to precompute some stuff, so that the actual created object is `(FragmentInit. [name] nil reference-to-code-generated-by-macro)`. The macro pulled out the thing than can change in the Hiccup into the `[name]` vals structure, and the generated code will only diff that. Similarly the components generate a [ComponentInit](https://github.com/thheller/shadow-grove/blob/2715cb8d163b4a1e37cc4d2b4e402b26d073ff5c/src/main/shadow/grove/components.cljs#L579-L588). The only goal here being that these are as cheap as possible to construct and diff later.

Since you asked how I got the perf I guess I can walk you through how the hiccup implementation works. Basically hiccup is already its own initializer object, so I extend the `IConstruct` protocol onto vectors, as done [here](https://github.com/thheller/shadow-grove/blob/2715cb8d163b4a1e37cc4d2b4e402b26d073ff5c/src/main/shadow/arborist/interpreted.cljs#L342-L354).

[as-managed-vector](https://github.com/thheller/shadow-grove/blob/2715cb8d163b4a1e37cc4d2b4e402b26d073ff5c/src/main/shadow/arborist/interpreted.cljs#L233-L254) then does the actual first work of constructing the managed instance. Not to happy with the naming here, but by managed I basically mean a live node in the tree this is managing. It then constructs the actual DOM node, sets its attributes and an optimization I added recently checks if all all children in the vector represent text. If so it can just assign `textContent`, which is a bit faster than going through the protocol upgrade path. If not it just calls the [as-managed](https://github.com/thheller/shadow-grove/blob/2715cb8d163b4a1e37cc4d2b4e402b26d073ff5c/src/main/shadow/arborist/interpreted.cljs#L253) `IConstruct` protocol function on each child. Basically just recursing down the hiccup if it finds another vector. Some more basic impls such as `String` can be found [here](https://github.com/thheller/shadow-grove/blob/2715cb8d163b4a1e37cc4d2b4e402b26d073ff5c/src/main/shadow/arborist/common.cljs#L154-L166).

Thats basically all there is to the initial construction of the tree, what the caller ends up with is a single "managed" root node. How the upgrade process is handled I covered in the bit outdated [shadow-arborist](https://github.com/thheller/shadow-arborist) README. The principle is still accurate. First check `(supports? managed new-init)`, if thats true `(dom-sync! managed next-init)`. I'm sure you can follow the [vector dom-sync!](https://github.com/thheller/shadow-grove/blob/2715cb8d163b4a1e37cc4d2b4e402b26d073ff5c/src/main/shadow/arborist/interpreted.cljs#L155-L222) implementation. In the end its not a whole lot of code for the interpreted hiccup support.

The `IConstruct` protocol is `:extend-via-metadata`, so just data with some metadata is totally possible. I have done that before, but migrated pretty much everything to `deftype` because it generates the most efficient code for this use case. I often opted for performance, so adding some more convenience is certainly possible.

I guess the takeaway being that the implementation for hiccup vectors, or `arborist` for that matter, has no notion of what a component is, and don't need to. It all ends up neatly hidden behind the protocols. I also described how [collections](https://github.com/thheller/shadow-grove/blob/master/doc/arch/collections.md) work, since they remove the ambiguity hiccup otherwise have regarding keyed/non-keyed collections. You could however just as easily extend the `IConstruct` protocols for the seq  types. Having specialized implementations is where most of the performance comes from though, since there is never any "guessing" in the algos trying to figure out what its working with.

**Comment by thheller** [comment]
I added an implementation to support the trendy "Signals", using [flex](https://github.com/lilactown/flex) since I didn't really want to write my own signals lib. Might be another useful reference, even if just for the implementation. This one is cheating a bit and just delegating to a common implementation, but you get the idea. Protocols are sweat.

https://github.com/thheller/shadow-grove/blob/master/src/dev/dummy/flex.cljs#L16-L51

**Comment by thheller** [comment]
I left some notes for myself to see if I can cover the gaps that are currently missing in support compared to replicant.

https://github.com/thheller/shadow-grove/blob/master/src/dev/dummy/replicant.cljs#L22

Definitely should have that and will think about it.

**Comment by thheller** [comment]
I was just looking into how replicant handles `:replicant/key` and I think I found the benchmark regression you mentioned. The Benchmark still seems to be using `:key`.

https://github.com/cjohansen/js-framework-benchmark/blob/02b82c6518cf1b5462a4a9f973baf32004c67f64/frameworks/keyed/replicant/src/demo/main.cljs#L6

**Comment by cjohansen** [comment]
> I have been there myself. I decided not to use it because it creates a bit of a "maintenance hassle", meaning that you have to put the implementation for that keyword somewhere. So, the immediate first candidate becomes a defmulti or some other kind of registry atom. The hassle being that we cannot rely on your code structure to provide these, or my larger pet peeve being that dead-code elimination cannot work. Thus all registered components stay alive, even if never used. The the build-sized-obsessed me that didn't seem ideal.

I haven't decided on the registry yet, but will likely not use a multi-method. For the time being I have implemented this by passing a map of keyword -> fn. So long as you have this option you can also have effective dead code elimination. I want Replicant to be able to render fully serialisable data, and thus I don't want to require the use of opaque runtime objects.

In the grand scheme of things I'm a little torn between making Replicant play nice in a bigger ecosystem, and allowing "whatever" to render inside Replicant, as that will enable all sorts of patterns I have deliberately designed out of it (components with local state, etc).

> But in the end the way this always works is the for example calling (a-grove-component) does not actually immediately construct the component/DOM. It creates an initializer object, which I have struggled to name correctly. I kinda like "Seed" since it fits into this whole tree-analogy theme. The idea being that you place the seed and a tree grows out of it.

"Seed" is a very good name for this in arborists's context 😊 

I've looked a little at the code samples you linked to, but will need some more time to study it fully. Having written an implementation myself I know that this stuff is not super straight forward 😅 

I'm curious: how have you approached testing? I looked around in the tests directory, but didn't find a lot of detailed tests. I built a pretty comprehensible suite of tests to ensure Replicant performs the right DOM operations in various cases. In particular I made sure it can reuse and move nodes around without recreating them in order to not trigger transitions at the wrong times etc: https://github.com/cjohansen/replicant/blob/main/test/replicant/core_test.clj I had a lot of use for the protocol that's in front of the DOM API with these.

> I added an implementation to support the trendy "Signals", using [flex](https://github.com/lilactown/flex) since I didn't really want to write my own signals lib.

I don't know what these are 😅 

----

If we're going to shoot for some shared protocols to power these libs then maybe there would be some merit in a separate library that just contains the protocols and not any specific implementations. I haven't tried using your protocols in Replicant, so not sure how that would work. I did notice that your protocol specifies different steps than the ones I took. I'm also unsure if a shared protocol needs to specify all the steps of the algorithm, maybe it's enough that it specifies how something becomes a DOM node and how it updates an existing DOM node. I'm not sure, you've obviously thought more about this than me.

**Comment by thheller** [comment]
> In the grand scheme of things I'm a little torn between making Replicant play nice in a bigger ecosystem, and allowing "whatever" to render inside Replicant, as that will enable all sorts of patterns I have deliberately designed out of it (components with local state, etc).

After having gone through some of Replicants features I agree. While it is certainly possible to do most of them via my protocols, many become harder and less efficient. In the end I believe a dedicated hiccup impl could be faster than something "generic" like my protocols. In the end my primary goals include some of the stuff you explicitely do not want.

So, a shared protocol would likely just hurt and also create loopholes for people to create stuff you didn't want.

I guess an open question is how you intend to interop with 3rd party libs? I haven't seen anything that would expose an actual DOM node?

---

> how have you approached testing?

Tests are mostly missing currently, which I do need to fix. I will likely write them using `jsdom` as I started [here](https://github.com/thheller/shadow-grove/blob/master/src/test/shadow/grove_test.cljs). I like your way, but I'm not willing to sacrifice the overhead it brings. In the end this is still reasonably easy to test against either the actual DOM or JSDOM. Given that I allow or even encourage direct DOM interop this is required.

Thanks for the discussion though. I certainly changed my mind on the serializability issue and implemented some more stuff to enable that.

**Comment by cjohansen** [comment]
> After having gone through some of Replicants features I agree. While it is certainly possible to do most of them via my protocols, many become harder and less efficient. In the end I believe a dedicated hiccup impl could be faster than something "generic" like my protocols.

If that's the case, I need to up my game, at least according to the benchmarks 😅 

> I guess an open question is how you intend to interop with 3rd party libs? I haven't seen anything that would expose an actual DOM node?

You can access DOM nodes via the life-cycle hook `:replicant/on-update`. The [example in the README](https://github.com/cjohansen/replicant?tab=readme-ov-file#life-cycle-hooks) isn't very clear, I'll fix that. Basically:

```clj
(require '[replicant.dom :as replicant])

(replicant/render
 (js/document.getElementById "app")
 [:h1 {:replicant/on-update
       (fn [e]
         (js/console.log "DOM Node:" (:replicant/node e)))}
  "Hi!"])
```

Other than that I haven't put much thought into interop with 3rd party libraries. I designed Replicant to be a pure rendering library, so interop is expected to happen elsewhere and produce hiccup that you ask to render.

Personally, I would never mix and match component/rendering libraries in the same code base. I generally don't even like using third party components/UI libraries (outside of low-level utilities like tailwind etc). I find it to be a much too volatile level to share code on, and there are too many breaking changes. 

As a side note, I saw [this tweet](https://twitter.com/garybernhardt/status/1757535056216854766) this morning, and relate to it very much 😊

> Tests are mostly missing currently, which I do need to fix. I will likely write them using jsdom as I started [here](https://github.com/thheller/shadow-grove/blob/master/src/test/shadow/grove_test.cljs). I like your way, but I'm not willing to sacrifice the overhead it brings.

Interesting. I had assumed the overhead is minimal, as it's one protocol jump for each DOM operation. I will have to bench out the cost of this abstraction.

> Thanks for the discussion though. I certainly changed my mind on the serializability issue and implemented some more stuff to enable that.

Likewise, thanks, it's been interesting to hear your thoughts on this. As I mentioned earlier, you have obviously put a lot more thought into the desired ecosystem around these tools. I generally agree with you that protocols are awesome for libraries, and in I think you have made excellent choices for shadow-grove, as it opens up for custom component implementations, and even different programming models, as exemplified by some of your POCs. I will keep an eye on this stuff.

**Comment by cjohansen** [comment]
> Same here, although I cannot claim that stuff I have written myself doesn't come back to bite me later sometimes too.

Oh, for sure 😅 I'm not saying I'm better than everyone else. But when you make a library out of a UI component you will invariably end up support a lot more variability and features than any one consumer is going to use. So now users of this library will subscribe to an interface that may change for any number of reasons, even though they only use a single feature, say. This makes things more volatile and brittle than more focused local solutions. Additionally, for React specifically, the JS community isn't exactly known for their stellar track record for backwards compatibility.

> Good to know, so there are "holes" already. Thought that was supposed to be data-only too.

Well, yes, you can get a hold of a DOM node. The handler itself can be represented by data though:

```clj
(require '[replicant.dom :as replicant])

(replicant/set-dispatch!
 (fn [e data]
   (js/console.log "DOM Node:" (:replicant/node e))
   (js/console.log "Hook data" data)
   (prn "Click!")))

(replicant/render
 (js/document.getElementById "app")
 [:h1 {:replicant/on-update [:custom :data "Here"]}
  "Hi!"])
```

Thanks for the pointers on protocols, I learned something new 😊  I actually did run the benchmark without the protocol, and it made more or less no difference. I'll replace the DOM implementation with a deftype though.

I did memoize the `parse-tag` at some point, but seem to remember not seeing enough of a boost to take on the additionally memory consumption. I'll revisit this and see.

**Comment by thheller** [comment]
> Additionally, for React specifically, the JS community isn't exactly known for their stellar track record for backwards compatibility.

Indeed.

BTW one thing I didn't see is that the benchmarks now (or maybe always) can show how much time is actually spent in JS code. The default also counts all the actual browser DOM work. Which often dominates with a very large percentage.

CLJS will always be a bit behind in raw performance due to all the datastructure overhead, but I noticed a much larger difference when I compared my fragments vs my interpreted mode. So in the end hiccup always has to do a lot more work. Might be easier to see the differences for small tweaks with those numbers though, when you actually substract the browser time.

But in the end all this shows is that everything we do is probably fast enough. Just gotta avoid some obviously dumb things and the burden shifts to reducing the amount of work done at all. Which is my focus in grove, wrote about that [here](https://github.com/thheller/shadow-grove/blob/master/doc/arch/why-components.md) and [here](https://github.com/thheller/shadow-grove/blob/master/doc/what-the-heck-just-happened.md). Which is I guess the main crux of where our philosophies diverge.

**Comment by cjohansen** [comment]
Indeed, this seem to be where our goals differ 😊 

> The promise of React was something like ui = render(data), as in building your UI as a function of your data.

I fell in love with this eye on first sight back in 2013, and this is the world I want to work in. Thus, the goal of Replicant is to be able to do this reasonably fast enough - programming model first. It will never be a good choice for very graphical games etc, but it'll work well for the kinds of applications I spend the most time building 😊
