### ISSUE TITLE
Is it possible to handle local state?

### ISSUE THREAD

**Issue by faust45** [cjohansen/replicant#17]
If I want to have component like dropdowns with local state, how I can handle local state with replicant?
Thanks!

**Comment by cjohansen** [comment]
Replicant is a pure rendering library, and deliberately does not provide any state management, including component-local state. It only knows how to render hiccup to DOM. Replicant assumes state is handled separately from rendering.

**Comment by faust45** [comment]
Thanks for response! Yes i understand, replicant is pure rendering. But can you give me any idea, how I can implement local state?

**Comment by cjohansen** [comment]
You can't, really. If you want components with local state, Replicant is not the tool you're looking for.

As I mentioned, Replicant expects state to be handled outside of the render loop. This means that it encourages global state, so even the dropdown would keep its state globally.
