### ISSUE TITLE
API for events and life cycles

### ISSUE THREAD

**Issue by larstvei** [cjohansen/replicant#19]
Hi again, and thank you for your work on Replicant.

I would like to discuss a change to make the API for events and life-cycle hooks more uniform.

Currently, Replicant provides a single function `set-dispatch!` that you can bind to a function that handles all events and life-cycles. As I understand it, the function is called with three arguments for event data (replicant-data, the js event and the handler-data), and two arguments for life-cycles (the replicant-data and the hook-data). It seems that any dispatch function that will deal with both events and life-cycles would need to first dispatch on `:replicant/event` (maybe using a multimethod).

I would suggest one of two changes:

-   Separate `set-dispatch!` into e.g. `set-dispatch-event!` and `set-dispatch-life-cycle!`.
-   Make the arguments to events and life-cycles more consistent.

A separation would make the difference in arity a non-issue.

However, i think making the arguments more consistent is closer to the original design, and might turn out nicer, allowing all dynamic behavior to get funneled through the same function.

One way of unifying it might look something like:

-   A dispatch function takes exactly two arguments:
    1.  The Replicant data.
    2.  The data the user specified in the hiccup.
-   The Replicant data could include something like the following (mostly based on is already there):
    -   Whether it is a DOM event or life-cycle event
    -   What caused the event: dom-event, mount, unmount or update\*
    -   The DOM node (same as `:replicant/node`, but use the target for DOM events)

The asterisk\* is there to note that I see that this might conflate DOM events and life-cycles. To me this seems fine, because it captures *what caused this data to end up in my handler*, which is sufficient for me to know what I need to do with it.

To make things a bit more concrete, let me make the suggestion based on a simple example:

```clojure
(replicant/render
  (js/document.getElementById "app")
  [:h1 {:on {:click [:event]}
        :replicant/on-update [:life-cycle]} "Click me"])
```

Currently, DOM event causes the following arguments to be passed to the dispatch function:

-   Replicant data:
    
    ```clojure
    {:replicant/event :replicant.event/dom-event}
    ```
-   Javascript event:
    
    ```clojure
    #object[PointerEvet [object PointerEvent]]
    ```
-   Data from the hiccup:
    
    ```clojure
    [:event]
    ```

And the life-cycle hooks passes these arguments:

-   Replicant data:
    
    ```clojure
    {:replicant/event :replicant.event/life-cycle,
     :replicant/life-cycle :replicant/mount,
     :replicant/node #object[HTMLHeadingElement [object HTMLHeadingElement]]}
    ```
-   The data from the hiccup:
    
    ```clojure
    [:life-cycle]
    ```

My suggestion would be to have DOM events result in arguments like this:

-   Replicant data:
    
    ```clojure
    {:replicant/event :replicant.event/dom-event
     :replicant/js-event #object[PointerEvet [object PointerEvent]]
     :replicant/node #object[HTMLHeadingElement [object HTMLHeadingElement]]}
    ```
    
    Where `:replicant/node` is bound to the `target` of the event.
-   Data from the hiccup:
    
    ```clojure
    [:event]
    ```

And life-cycles result in arguments like this:

-   Replicant data:
    
    ```clojure
    {:replicant/event :replicant.event/mount,
     :replicant/node #object[HTMLHeadingElement [object HTMLHeadingElement]]}
    ```
-   The data from the hiccup:
    
    ```clojure
    [:life-cycle]
    ```

Somehow related, I am wondering if it would be good to allow `:replicant/on-mount` and `:replicant/on-unmount` in the hiccup, because I imagine a lot of the time, a dispatch function would only do something for some of the life-cycle events. Perhaps even let the life cycle events be of the form `{:on {:replicant/mount ...}}`, `{:on {:replicant/unmount ...}}` and `{:on {:replicant/update ...}}`?

Note that I am not claiming this to be the ideal design or anything, but I wanted to make a somewhat concrete suggestion to illustrate the direction I had in mind. Let me know if you are open to changes along these lines, in which case I could try to make the changes and provide a pull request.

**Comment by cjohansen** [comment]
Thanks for the thoughtful input! This part is obviously not finished as is. One function, two different signatures - what was I thinking 🙈 

I read this proposal, let it sink in, then read it again. I was initially undecided on what would be better: two dispatches, or stream-lined arities. I really like your suggestion. Stream-lining the arities - and the shape of the received data - reduces the amount of concepts: less documentation, less to learn, easier to use 👍 However, it is possible to streamline them _and_ provide different dispatches. I can't quite decide if that's necessary, or even benefitial.

I do wonder if we could come up with a name for `:replicant/event` that avoids confusion with the event object. I don't have any good suggestions right now, but wanted to ask in case you have some.

I had originally thought that offering only a single life-cycle hook was the more elegant choice, as mount/unmount can be determined from the data. However, while reading your proposal, I became aware of how this effectively forces you to use a function (e.g. not use data-based dispatch) in order to make that decision. So in light of that I support dedicated `:replicant/on-mount` and `:replicant/on-unmount`.

I'm undecided on having life-cycle events in `{:on {,,,}}`. On one hand, the suggested change would make events and life-cycles more closely related, which means they go together, on the other hand one is from the browser, the other from replicant. Maybe that isn't very important? Need to stew on this a little longer.

**Comment by larstvei** [comment]
Thank you, I really appreciate that you took the time to think this over.

Having both should work, but it might complicate things a bit, as you have to make a decision on what should happen if you specify both a general handler *and* more specific handlers. Perhaps specifying both should give an error, or maybe specifying both should be inexpressible (e.g. that you either pass `set-dispatch!` a function, or a map with `{:replicant/event-handler ... :replicant/life-cycle-handler ...}` or something). My thinking is that it opens up a couple of questions, which a user might have to consider too, at which point it might not be worth it. If the replicant-data contains information of whether it is a DOM event or a life-cycle, then anyone who wants to keep these separated may do so e.g. using a multimethod.

I strongly agree on finding another word than event, as it is very easily conflated. Perhaps `:replicant/trigger` could be a name that captures what caused the event (`:replicant/dom-event`, `:replicant/mount`, etc)? Then perhaps `:replicant/trigger-type` could have values `:replicant.trigger/dom-event` or `:replicant.trigger/life-cycle`.

I am not sure why, but i have a feeling that names that the user is expected to interact with (e.g. dispatch on) should not contain dots 😅

As for the `{:on {,,,}}`, I don't think it is important, it just kind of got sucked into the "let's unify all the things!" train of thought. If the keys are namespaced with `replicant/...`, then I think it is pretty clear that these can have some Replicant-specific semantics, so I don't see any pitfalls with it.

**Comment by cjohansen** [comment]
> Having both should work, but it might complicate things a bit, as you have to make a decision on what should happen if you specify both a general handler and more specific handlers.

I was not clear enough. I did not mean this kind of "both" - I agree this is not a good idea. My point was that aligning the signatures would be a good idea even if we provided two different dispatches - e.g. both align signatures, and split in two dispatches 😅 

Let's conclude: One dispatch, streamlined arity/signature.

----

Re: naming. I like "trigger". I think "cause" could also work. And like you point out, there are two levels, but I want to rearrange your suggestion a little:

- One has one of these values: `dom-event`, `life-cycle` (these need to be qualified)
- One has one of these values: `mount`, `unmount`, `update` (these need to be qualified) or a DOM event type, e.g. `:dom.event/click` (basically `(keyword "dom.event" (.-type e))`)

I agree that the keys here should not have dots in them, but I like the pattern where type-identifiers like `:NS/NAME` keys have values like `:NS.TYPE/TYPE`.

Maybe something like:

- `:replicant/trigger-kind` one of `#{:replicant.trigger/dom-event :replicant.trigger/life-cycle}`
- `:replicant/trigger-detail` one of `#{:dom.event/click :dom.event/mouseover ... :replicant.life-cycle/mount :replicant.life-cycle/unmount :replicant.life-cycle/update}`

**Comment by cjohansen** [comment]
Ok, a quick later and I already changed my mind 😅 I don't think there's much value in duplicating the `(.-type e)` into the replicant map. So updated suggestion:

- `:replicant/trigger` is one of `:replicant.trigger/dom-event` or `:replicant.trigger/life-cycle`
- `:replicant/life-cycle` is one of `:replicant.life-cycle/mount`, `:replicant.life-cycle/unmount` or `:replicant.life-cycle/update` when `:replicant/trigger` is `:replicant.trigger/life-cycle`

This avoids finding two new names.

**Comment by larstvei** [comment]
Sorry for not replying. I think this all looks really good. Do you want me to have a go at it?
