### ISSUE TITLE
How do you set the checked property of a checkbox?

### ISSUE THREAD

**Issue by evaogbe** [cjohansen/replicant#46]
I'm trying to do TodoMVC. It has a checkbox per todo and another toggle all checkbox for all of them. I set up the checkboxes like this:

```clojure
;; For todo
[:input.toggle {:type "checkbox"
                      :checked completed?
                      :id (str "todo-" id)
                      :on {:change [::toggle-complete id]}}]
;; For toggle all
[:input#toggle-all.toggle-all {:type "checkbox"
                                       :checked (= (count completed) (count todos))
                                       :on {:change [::toggle-all]}}]
```

Because Replicant uses setAttribute, the checked state is only being set one time.

What's the idiomatic way of setting the checked property?

**Comment by cjohansen** [comment]
You're doing the right thing, Replicant is not 😅 I just pushed a fix that makes Replicant control this attribute with the DOM property instead. Let me know if it solves your problem.

**Comment by evaogbe** [comment]
That fixed the issue thanks!

A small suggestion: you could do something like React where they have a way of setting the value and checked properties and a separate way of setting the value and checked attributes (defaultValue and defaultChecked). That gives people flexibility for if they want to set the value/checked once but they don't want to fully control the component.

**Comment by cjohansen** [comment]
Good idea! I just added this for value/selected/checked.
