### ISSUE TITLE
Layout manager 

### ISSUE THREAD

**Issue by awb99** [cjohansen/replicant#47]
Do you have a recommendation how to integrate this react
Based layout manager to replicant: https://github.com/caplin/FlexLayout

I imagine it would mean having dozens of replicant root elements
In the dom that get created by some wrapper that can be sent to react.

I hope my post here is not too weird.
But unfortunately reacts ecosystem is huge and so far I haven't 
Found something equivalent.

I think integration of react with replicant could be easy .. but the
Case of a layout manager is not the typical ui component.

Thanks!

**Comment by cjohansen** [comment]
There is no way to integrate react components with replicant aside from calling render with the DOM node in a life cycle hook. But I wouldn't recommend it.

The idea of replicant is to write completely data-driven user interfaces in ClojureScript. If you want to integrate with React there are better options, such as reagent, uix, helix etc.

If you like the layout module, maybe think about how such a thing could be written data-driven in pure ClojureScript 😊
