### ISSUE TITLE
Safe to add sub dom nodes?

### ISSUE THREAD

**Issue by awb99** [cjohansen/replicant#48]
To use highcharts.js with replicant I have to call the 
Highchart render method with a dom node. I can 
Do that by subscribing to events. My question is 
If the dom element's created that way would be 
Overridden by replicant. Or if there is a tag I can 
Set so that this does not happen. 
Thanks!

**Comment by cjohansen** [comment]
Unless you start returning hiccup inside the target element, replicant is not going to mess with the child nodes.

Using `:replicant/on-render` to hook in third parties in the DOM is completely safe, and one of the intended uses for it 👍

**Comment by awb99** [comment]
Thanks!
