### ISSUE TITLE
string keys for style crash in non-obvious way

### ISSUE THREAD

**Issue by gaverhae** [cjohansen/replicant#49]
Using string keys for the `:style` map on a DOM object results in a very hard-to-guess and hard-to-track error when the associated value changes. As a concrete example, with [this small-ish repro repo](https://github.com/gaverhae/replicant-style-string-issue/blob/1a06718dd03784c1685fa7665e7d00f110a2b9a9/cljs/t/core.cljs#L17-L27), the error is:

```
[Error] TypeError: p1__41083_SHARP_.call is not a function. (In 'p1__41083_SHARP_.call(null,new_styles)', 'p1__41083_SHARP_.call' is undefined)
	cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (ioc_helpers.js:104)
	(anonymous function) (async.js:4253)
	(anonymous function) (async.js:586)
	(anonymous function) (channels.js:209)
	cljs$core$async$impl$dispatch$process_messages (dispatch.js:20)
	(anonymous function) (nexttick.js:195)
```

I suppose it doesn't help that this all happens in a `core.async` loop.

Not accepting strings for keys in the `:style` map is a valid design choice, but I would prefer if it came with at least one of the following:
- Explicit statement in the README.
- A failure with a clear error message on first render.
- A more understandable error message on second render.

Note that the error does not trigger on the first render, nor on any subsequent render that happens to not change the associated value. It only fails on the first "re-render" that actually tries to change the vlues, making this hard to track.

I made a [small repro repo](https://github.com/gaverhae/replicant-style-string-issue); repro steps with that repo are:

1. `git clone git@github.com:gaverhae/replicant-style-string-issue.git`
2. `cd replicant-style-string-issue`
3. Figure out some way to get Leiningen on your system. If you have Nix and direnv installed, you can get it with `direnv allow`.
4. `lein repl`
5. `(go)` in the REPL. This should open a browser on localhost:8000.
6. Click the "click me" (unstyled) button. This works as expected.
7. In the code, swap the comment on [the style map](https://github.com/gaverhae/replicant-style-string-issue/blob/1a06718dd03784c1685fa7665e7d00f110a2b9a9/cljs/t/core.cljs#L21-L22).
8. Refresh the browser and click the button again. Now it crashes. You may need to open the browser console to see it.

To make it extra clear, this works:

```clojure
[:div {:style {:translate (computed-value)}}]
```

while this fails in a non-obvious way:

```clojure
[:div {:style {"translate" (computed-value)}}]
```

**Comment by cjohansen** [comment]
Thanks for the detailed report, and ouch! Sorry about this @gaverhae 😅 This is simply an oversight on my part. I'll have a look at it.

**Comment by cjohansen** [comment]
There actually was a warning related to this, but it only triggered when the key was not a string, symbol or a keyword. I made the assertion stricter, which will show you the warning in development, but then also fixed the error so your code will work 😊 

![CleanShot 2024-11-08 at 16 12 05@2x](https://github.com/user-attachments/assets/86e7836c-7401-42c8-bc80-32c566055bda)
